import SwiftUI
import UIKit

/// Renders any family-tree view into a shareable PNG with the Memento
/// watermark along the bottom. Used by the pedigree, the Business ladder
/// and each person's Family-tab tree — one pipeline, one look.
enum TreeImageExport {

    /// A rendered export ready for the share sheet.
    struct Item: Identifiable {
        let id = UUID()
        let url: URL
    }

    /// Composes `content` over `background` with the watermark bar, renders
    /// at 3× and writes a PNG the share sheet can hand to AirDrop, Messages,
    /// Photos or Files.
    @MainActor
    static func export(_ content: some View, background: Color, filename: String) -> Item? {
        let framed = VStack(spacing: 14) {
            content
            watermark
        }
        .padding(24)
        .background(background)

        let renderer = ImageRenderer(content: framed)
        renderer.scale = 3
        guard let image = renderer.uiImage, let data = image.pngData() else { return nil }

        let safeName = filename.replacingOccurrences(of: "/", with: "-")
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("\(safeName).png")
        do {
            try data.write(to: url)
            return Item(url: url)
        } catch {
            return nil
        }
    }

    /// The bottom bar: mark + "Generated by Memento" in the brand serif.
    private static var watermark: some View {
        HStack(spacing: 8) {
            LogoMark(size: 22)
            Text("Generated by Memento")
                .font(.system(.footnote, design: .serif))
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity)
    }
}

/// UIActivityViewController bridged for SwiftUI — presented as a sheet's
/// content so it needs no popover anchoring on iPad or the Mac.
struct ActivityShareSheet: UIViewControllerRepresentable {
    let url: URL

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: [url], applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}
